const db = require("../db");
const Region = require("../models/region");

db.on("error", console.error.bind(console, "MongoDB connection error:"));

const main = async () => {
  const regions = [
    {
      name: "Targon",
      championsInRegion: [
        "Aphelios",
        "Aurelion Sol",
        "Diana",
        "Leona",
        "Pantheon",
        "Soraka",
        "Taric",
        "Zoe",
      ],
      momument: "Mount Targon",
    },
    {
      name: "Shurima",
      championsInRegion: [
        "Akshan",
        "Amumu",
        "Azir",
        "K'sante",
        "Naafiri",
        "Nasus",
        "Rammus",
        "Renekton",
        "Sivir",
        "Skarner",
        "Taliyah",
        "Xerath",
      ],
      momument: "The Sun Disc",
    },
    {
      name: "Ixtal",
      championsInRegion: [
        "Malphite",
        "Milio",
        "Neeko",
        "Nidalee",
        "Qiyana",
        "Rengar",
        "Zyra",
      ],
      momument: "Ixaocan",
    },
    {
      name: "Shadow Isles",
      championsInRegion: [
        "Elise",
        "Gwen",
        "Hecarim",
        "Kalista",
        "Karthus",
        "Maokai",
        "Thresh",
        "Vex",
        "Viego",
        "Yorick",
      ],
      momument: "Vaults Of Helia",
    },
    {
      name: "Bilgewater",
      championsInRegion: [
        "Fizz",
        "Gangplank",
        "Graves",
        "Illaoi",
        "Miss Fortune",
        "Nautilus",
        "Pyke",
        "Tahm Kench",
        "Twisted Fate",
      ],
      momument: "Slaughter Docks",
    },
    {
      name: "Bandle City",
      championsInRegion: [
        "Corki",
        "Lulu",
        "Rumble",
        "Teemo",
        "Tristana",
        "Veigar",
        "Yuumi",
      ],
      momument: "The Bandle Tree",
    },
    {
      name: "Demacia",
      championsInRegion: [
        "Fiora",
        "Galio",
        "Garen",
        "Jarvan IV",
        "Kayle",
        "Lucian",
        "Lux",
        "Morgana",
        "Poppy",
        "Quinn",
        "Senna",
        "Shyvana",
        "Sona",
        "Sylas",
        "Vayne",
        "Xin Zhao",
      ],
      momument: "The Great City Of Demacia",
    },
    {
      name: "Noxus",
      championsInRegion: [
        "Briar",
        "Cassiopeia",
        "Darius",
        "Draven",
        "Katarina",
        "Kled",
        "Leblanc",
        "Mordekaiser",
        "Rell",
        "Riven",
        "Samira",
        "Sion",
        "Swain",
        "Talon",
        "Vladimir",
      ],
      momument: "The Immortal Bastion",
    },
    {
      name: "Ionia",
      championsInRegion: [
        "Ahri",
        "Akali",
        "Hwei",
        "Irelia",
        "Ivern",
        "Jhin",
        "Karma",
        "Kayn",
        "Kennen",
        "Lee Sin",
        "Lillia",
        "Master Yi",
        "Wukong",
        "Rakan",
        "Sett",
        "Shen",
        "Syndra",
        "Varus",
        "Xayah",
        "Yasuo",
        "Yone",
        "Zed",
      ],
      momument: "The Placidium Of Navori",
    },
    {
      name: "Plitover & Zaun",
      championsInRegion: [
        "Caitlyn",
        "Camille",
        "Ezreal",
        "Heimerdinger",
        "Jayce",
        "Orianna",
        "Seraphine",
        "Vi",
        "Blitzcrank",
        "Dr.Mundo",
        "Ekko",
        "Janna",
        "Jinx",
        "Renata Glasc",
        "Singed",
        "Twitch",
        "Urgot",
        "Viktor",
        "Warwick",
        "Zac",
        "Ziggs",
        "Zeri",
      ],
      momument: "Hexgates",
    },
    {
      name: "Freljord",
      championsInRegion: [
        "Anivia",
        "Ashe",
        "Braum",
        "Gnar",
        "Gragas",
        "Lissandra",
        "Nunu & Willump",
        "Olaf",
        "Ornn",
        "Sejuani",
        "Trundle",
        "Tryndamere",
        "Udyr",
        "Volibear",
      ],
      momument: "The Frostguard Citadel",
    },
    {
      name: "Runeterran",
      championsInRegion: [
        "Aatrox",
        "Alistar",
        "Annie",
        "Bard",
        "Brand",
        "Evelynn",
        "Fiddlesticks",
        "Jax",
        "Kindred",
        "Nami",
        "Nocturne",
        "Ryze",
        "Shaco",
        "Smolder",
        "Zilean",
      ],
    },
    {
      name: "The Void",
      championsInRegion: [
        "Belveth",
        "Cho'Gath",
        "Kai'Sa",
        "Kassadin",
        "Kha'Zix",
        "Kog'Maw",
        "Malzahar",
        "Rek'Sai",
        "Vel'Koz",
      ],
      momument: "Icathia",
    },
  ];
  try {
    await Region.insertMany(regions);
    console.log("Welcome to Runeterra!");
  } catch (error) {
    console.error("Error seeding data:", error);
  }
};
const run = async () => {
  await main();
  db.close();
};
run();
